### ISSUE TITLE
Repo name and location issues

### ISSUE THREAD

**Issue by algernon** [keyboardio/Kaleidoscope-Plugin#7]
Calling the repository `Kaleidoscope-Plugin` and putting it under `Arduino-Boards/libraries` too. First, this is not an Arduino library, so the IDE will complain about it. Second, it is not a plugin, nor a base class or anything like it. It contains tools to help build plugins.

We should find a better name, and a better place for it. If we do that, *all* of the plugins will have to be updated, to fix their makefiles.

**Comment by obra** [comment]
In the end, I broke the parts apart. Now I have to update a lot of makefiles
